"""add pricing model tiers

Revision ID: ee6d08dbcb61
Revises: f4ac50043e6d
Create Date: 2026-08-26 17:24:46.825359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee6d08dbcb61'
down_revision: Union[str, None] = 'f4ac50043e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('pricing_model', sa.String(length=30), server_default='on_demand', nullable=False))
    op.add_column('pricing', sa.Column('commitment_term_months', sa.Integer(), nullable=True))
    op.add_column('pricing', sa.Column('tier_min_unit', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False))
    op.add_column('pricing', sa.Column('tier_max_unit', sa.Numeric(precision=18, scale=4), nullable=True))
    op.create_index('ix_pricing_lookup', 'pricing', ['provider', 'region', 'resource_type', 'sku', 'pricing_model', 'effective_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_lookup', table_name='pricing')
    op.drop_column('pricing', 'tier_max_unit')
    op.drop_column('pricing', 'tier_min_unit')
    op.drop_column('pricing', 'commitment_term_months')
    op.drop_column('pricing', 'pricing_model')
    # ### end Alembic commands ###
