"""initial schema

Revision ID: f4ac50043e6d
Revises: 
Create Date: 2026-08-26 17:05:49.795749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4ac50043e6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_agent_name'), 'agent_events', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_events_event_type'), 'agent_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_events_session_id'), 'agent_events', ['session_id'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_runs_benchmark_name'), 'benchmark_runs', ['benchmark_name'], unique=False)
    op.create_index(op.f('ix_benchmark_runs_status'), 'benchmark_runs', ['status'], unique=False)
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_provider'), 'pricing', ['provider'], unique=False)
    op.create_index(op.f('ix_pricing_region'), 'pricing', ['region'], unique=False)
    op.create_index(op.f('ix_pricing_resource_type'), 'pricing', ['resource_type'], unique=False)
    op.create_index(op.f('ix_pricing_sku'), 'pricing', ['sku'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_external_id'), 'resources', ['external_id'], unique=True)
    op.create_index(op.f('ix_resources_provider'), 'resources', ['provider'], unique=False)
    op.create_index(op.f('ix_resources_region'), 'resources', ['region'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('constraint_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraints_constraint_type'), 'constraints', ['constraint_type'], unique=False)
    op.create_index(op.f('ix_constraints_scenario_id'), 'constraints', ['scenario_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_run_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=150), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_benchmark_run_id'), 'evaluation_results', ['benchmark_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_metric_name'), 'evaluation_results', ['metric_name'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('target_metric', sa.String(length=50), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('training_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('run_metadata', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_resource_id'), 'forecasts', ['resource_id'], unique=False)
    op.create_index(op.f('ix_forecasts_status'), 'forecasts', ['status'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('objective', sa.String(length=100), nullable=False),
    sa.Column('solver_status', sa.String(length=50), nullable=True),
    sa.Column('objective_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_scenario_id'), 'optimization_runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_optimization_runs_status'), 'optimization_runs', ['status'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_provider'), 'usage_records', ['provider'], unique=False)
    op.create_index(op.f('ix_usage_records_resource_id'), 'usage_records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_usage_records_timestamp'), 'usage_records', ['timestamp'], unique=False)
    op.create_table('cost_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('predicted_date', sa.Date(), nullable=False),
    sa.Column('predicted_usage', sa.Float(), nullable=True),
    sa.Column('predicted_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('lower_bound', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_predictions_forecast_id'), 'cost_predictions', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_cost_predictions_predicted_date'), 'cost_predictions', ['predicted_date'], unique=False)
    op.create_index(op.f('ix_cost_predictions_resource_id'), 'cost_predictions', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_predictions_resource_id'), table_name='cost_predictions')
    op.drop_index(op.f('ix_cost_predictions_predicted_date'), table_name='cost_predictions')
    op.drop_index(op.f('ix_cost_predictions_forecast_id'), table_name='cost_predictions')
    op.drop_table('cost_predictions')
    op.drop_index(op.f('ix_usage_records_timestamp'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_resource_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_provider'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_optimization_runs_status'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_scenario_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_forecasts_status'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_resource_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_evaluation_results_metric_name'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_benchmark_run_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_constraints_scenario_id'), table_name='constraints')
    op.drop_index(op.f('ix_constraints_constraint_type'), table_name='constraints')
    op.drop_table('constraints')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_region'), table_name='resources')
    op.drop_index(op.f('ix_resources_provider'), table_name='resources')
    op.drop_index(op.f('ix_resources_external_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_pricing_sku'), table_name='pricing')
    op.drop_index(op.f('ix_pricing_resource_type'), table_name='pricing')
    op.drop_index(op.f('ix_pricing_region'), table_name='pricing')
    op.drop_index(op.f('ix_pricing_provider'), table_name='pricing')
    op.drop_table('pricing')
    op.drop_index(op.f('ix_benchmark_runs_status'), table_name='benchmark_runs')
    op.drop_index(op.f('ix_benchmark_runs_benchmark_name'), table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_index(op.f('ix_agent_events_session_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_event_type'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_agent_name'), table_name='agent_events')
    op.drop_table('agent_events')
    # ### end Alembic commands ###
